### ISSUE TITLE
Impressão Usando Conversor Paralelo para USB

### ISSUE THREAD

**Issue by adrbarros** [CDSInformatica/ImprimeTexto#1]
Carlos, como vai?
Uso essa sua biblioteca ha muitos anos e nunca me deixou na mão.

Eu tenho uma pergunta, quando é enviado a impressão direto para a porta LPT ou para alguma impressora instalada apontando a porta LPT (Generic/Text, EPSON Lx300), a imppressão é perfeita, se eu mandar 200 impressoes será impresso tudo e de forma bem rapida.

Agora quando eu uso um conversor Paralelo para USB, se eu mandar um texto pequeno, tipo Meia Folha Continua, a impressão nao sai completa, ai se eu mandar outra impressão, sai o restante da anterior mais o que mandei.
Outra se eu mandar 200 impressões direto, vai imprimindo tipo na impressão 20 a impressora começa a ficar lenta até não imprimir mais.

Você ja viu algo assim, e claro se for do seu conhecimento, algum meio de solucionar esse bug.

Obs.: isso acontece com todas as Libs para impressão matricial que eu conheço, quando se usa esse conversor (Paralelo->USB)

**Comment by carloscds** [comment]
@adrbarros Conversores são sempre um problema!!! Ideal neste caso é er um print server ou um computador em rede com porta paralela.

**Comment by adrbarros** [comment]
é situação complicada, hoje com tantos notebooks e o querendo usar matricial, o mais engraçado LX 300+ II e a LX 350 USB, funcionam perfeitamente, agora a primeira LX 300 não vai (Mas no PC com paralela é sem problemas). Agora é tentar convercer o cliente  a colocar um PC com porta paralela.

Grato pela resposta.
